#!/bin/bash

# DevSecOps HTML + Email Reporting Helper
# Purpose:
# - Convert text reports into clean HTML reports
# - Fix SonarQube HTML accessibility issue: <html lang="en">
# - Add readable colors for PASS / FAIL / WARN
# - Support optional email sending

create_html_report() {
  local TITLE="${1:-DevSecOps Report}"
  local TEXT_FILE="${2:-}"
  local HTML_FILE="${3:-}"

  if [ -z "$TEXT_FILE" ]; then
    echo "WARNING: Text report path is empty. Skipping HTML report generation."
    return 0
  fi

  if [ -z "$HTML_FILE" ]; then
    echo "WARNING: HTML report path is empty. Skipping HTML report generation."
    return 0
  fi

  if [ ! -f "$TEXT_FILE" ]; then
    echo "WARNING: Text report not found: $TEXT_FILE. Skipping HTML report generation."
    return 0
  fi
  local PASS_COUNT
  local FAIL_COUNT
  local WARN_COUNT
  local GENERATED_AT

  PASS_COUNT=$(grep -c "✅" "$TEXT_FILE" 2>/dev/null || echo 0)
  FAIL_COUNT=$(grep -c "❌" "$TEXT_FILE" 2>/dev/null || echo 0)
  WARN_COUNT=$(grep -c "⚠️" "$TEXT_FILE" 2>/dev/null || echo 0)
  GENERATED_AT=$(date +"%Y-%m-%d %H:%M:%S")

  mkdir -p "$(dirname "$HTML_FILE")"

  cat > "$HTML_FILE" <<EOF
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${TITLE}</title>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background: #0f172a;
  color: #e5e7eb;
  padding: 30px;
  margin: 0;
}
.container {
  max-width: 1200px;
  margin: auto;
  background: #1e293b;
  padding: 30px;
  border-radius: 14px;
}
h1 {
  color: #38bdf8;
  margin-bottom: 5px;
}
.subtitle {
  color: #94a3b8;
  margin-bottom: 25px;
}
.summary {
  margin-bottom: 25px;
}
.card {
  display: inline-block;
  padding: 18px;
  margin: 8px;
  border-radius: 10px;
  min-width: 130px;
  text-align: center;
  font-weight: bold;
}
.pass {
  background: #14532d;
  color: #bbf7d0;
}
.fail {
  background: #7f1d1d;
  color: #fecaca;
}
.warn {
  background: #78350f;
  color: #fde68a;
}
pre {
  background: #020617;
  color: #e5e7eb;
  padding: 20px;
  border-radius: 10px;
  overflow: auto;
  white-space: pre-wrap;
  line-height: 1.5;
  border: 1px solid #334155;
}
.footer {
  color: #94a3b8;
  margin-top: 25px;
  font-size: 13px;
}
.status-healthy {
  color: #22c55e;
  font-weight: bold;
}
.status-risk {
  color: #ef4444;
  font-weight: bold;
}
</style>
</head>
<body>
<div class="container">

<h1>${TITLE}</h1>
<div class="subtitle">Generated at: ${GENERATED_AT}</div>

<div class="summary">
  <div class="card pass">PASS<br>${PASS_COUNT}</div>
  <div class="card fail">FAIL<br>${FAIL_COUNT}</div>
  <div class="card warn">WARN<br>${WARN_COUNT}</div>
</div>

<h2>Full Report</h2>
<pre>
$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$TEXT_FILE")
</pre>

<div class="footer">
Generated by DevSecOps Lab Operations Toolkit
</div>

</div>
</body>
</html>
EOF

  echo "HTML report created: $HTML_FILE"
}

send_email_if_enabled() {
  local SUBJECT="$1"
  local HTML_FILE="$2"
  local EMAIL_TO="${EMAIL_TO:-}"

  if [ -z "$EMAIL_TO" ]; then
    echo "Email not sent. Set EMAIL_TO to enable email."
    return 0
  fi

  if [ ! -f "$HTML_FILE" ]; then
    echo "ERROR: HTML file not found: $HTML_FILE"
    return 1
  fi

  if command -v mail >/dev/null 2>&1; then
    mail -s "$SUBJECT" "$EMAIL_TO" < "$HTML_FILE"
    echo "Email sent to $EMAIL_TO"
  else
    echo "mail command not found. Install mailutils or configure SMTP later."
  fi
}
