#!/bin/bash

create_html_report() {
  TITLE="$1"
  TEXT_FILE="$2"
  HTML_FILE="$3"

  PASS_COUNT=$(grep -c "✅" "$TEXT_FILE" 2>/dev/null || echo 0)
  FAIL_COUNT=$(grep -c "❌" "$TEXT_FILE" 2>/dev/null || echo 0)
  WARN_COUNT=$(grep -c "⚠️" "$TEXT_FILE" 2>/dev/null || echo 0)

  cat > "$HTML_FILE" <<EOF
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>$TITLE</title>
<style>
body { font-family: Arial, sans-serif; background:#0f172a; color:#e5e7eb; padding:30px; }
.container { max-width:1200px; margin:auto; background:#1e293b; padding:30px; border-radius:14px; }
h1 { color:#38bdf8; }
.card { display:inline-block; padding:18px; margin:8px; border-radius:10px; min-width:120px; text-align:center; font-weight:bold; }
.pass { background:#14532d; color:#bbf7d0; }
.fail { background:#7f1d1d; color:#fecaca; }
.warn { background:#78350f; color:#fde68a; }
pre { background:#020617; padding:20px; border-radius:10px; overflow:auto; white-space:pre-wrap; line-height:1.5; }
.footer { color:#94a3b8; margin-top:25px; font-size:13px; }
</style>
</head>
<body>
<div class="container">
<h1>$TITLE</h1>

<div class="card pass">PASS<br>$PASS_COUNT</div>
<div class="card fail">FAIL<br>$FAIL_COUNT</div>
<div class="card warn">WARN<br>$WARN_COUNT</div>

<h2>Full Report</h2>
<pre>
$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$TEXT_FILE")
</pre>

<div class="footer">
Generated by DevSecOps Lab Operations Toolkit
</div>
</div>
</body>
</html>
EOF
}

send_email_if_enabled() {
  SUBJECT="$1"
  HTML_FILE="$2"
  EMAIL_TO="${EMAIL_TO:-}"

  if [ -z "$EMAIL_TO" ]; then
    echo "Email not sent. Set EMAIL_TO to enable email."
    return 0
  fi

  if command -v mail >/dev/null 2>&1; then
    mail -s "$SUBJECT" "$EMAIL_TO" < "$HTML_FILE"
    echo "Email sent to $EMAIL_TO"
  else
    echo "mail command not found. Install mailutils or configure SMTP later."
  fi
}
