sonar.projectKey=elhalawany-devops-lab
sonar.projectName=Elhalawany DevSecOps Lab
sonar.sources=.
sonar.exclusions=\
node_modules/**,\
backups/**,\
test-reports/**,\
recovery-reports/**,\
maintenance-reports/**,\
diagnostic-reports/**,\
daily-health-reports/**,\
k8s-admin-reports/**,\
terraform/.terraform/**,\
terraform/*.tfstate,\
terraform/*.tfstate.backup,\
*.log,\
.env*,\
*.tar.gz
