apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - postgres.yaml
  - node-app.yaml
  - nginx.yaml
  - hpa.yaml

commonLabels:
  project: node-app-devsecops-lab
  environment: dev
  managed-by: kustomize
